# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Christopher Hernandez
tagline:          Software Engineer
image:            ../../public/images/me2.jpg
description:      "CTO @ BarScan Developer @ Tandlr"
url:              /
baseurl:          http://chrishernandez.io

author:
  name:           'Christopher Hernandez'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
repository:       https://github.com/chernandez7/chernandez7.github.io
